---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: default
  labels:
    app: springboot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
      - name: springboot-demo
        image: sprintboot-demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        - name: spring.datasource.username
          value: demo
        - name: spring.datasource.password
          value: demo
# Enable it to read db password and secrets from aws secretsmanager
#        - name: aws.secret.datasource.config.secretName
#          value: /dev/dbsecrets
#        - name: aws.secret.other.config.secretName
#          value: /dev/othersecrets
        - name: spring.datasource.driver-class-name
          value: com.mysql.jdbc.Driver
