# This CI workflow can be triggered by PR creation or code push in PR, or manual trigger (after maven release)
# CI workflow for building, testing microservice, and publishing image to ECR
name: Maven Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: false

  push:
    branches: [ main ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  build-and-test:
    permissions:
      id-token: write # need this for OIDC
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yaml
    with:
      env: ${{ github.event.inputs.environment }}
      trufflehog-scan-flag: true
      maven-params: "-ntp -T 2C -Dmaven.test.skip=true -N"
      context: "."
    secrets: inherit
