# This CI workflow can be triggered by PR creation or code push in PR, or manual trigger (after maven release)
# CI workflow for building, testing microservice, and publishing image to ECR
name: Test Build

on:
  workflow_dispatch:
  
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test-working-dir:
    name: test working dir
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  src
    steps:
    
    - name: check path
      run: |
        if [[ -d /etc/chris ]]; then echo test_var1=true >>  $GITHUB_ENV; else echo test_var1=false >>  $GITHUB_ENV; fi
        
    - name: debug
      run: |
        echo ${{ env.test_var1 }}
    
    - name: Checkout Source Code
      uses: actions/checkout@v3
      
    - name: print repo name
      run: |
        echo ${{ github.event.repository.name }}
      
    - name: print pwd
      run: |
        pwd
        
    - name: access Dockerfile
      run: |
        cat ../Dockerfile
  
  
